### PR TITLE
Correcting #3 and #4

### PR DESCRIPTION
**Pull request by jd-develop**
And add the possibility to use `cd /Directory` if Direcroty exists in the active directory ^^

Please test and correct my code 😄

### CODE REVIEW

**Comment by jd-develop** [comment]
Hum, I did not build the .jar...

**Comment by Alexiscomete** [comment]
I think this might work
When I use ~ I have an erreur

**Comment by Alexiscomete** [comment]
Ok, I just forgot to add module ouput in jar configuration 🤣 :octocat:

**Comment by Alexiscomete** [comment]
@jd-develop what do you think ?

**Comment by jd-develop** [comment]
@Alexiscomete 
Looks nice and works fine ^^
You can merge :)

**Pull request merged**
